name: Compile xpwn and idevicererestore
on: [push]
jobs:
  xpwn-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: |
          cd ./src/xpwn
          ./compile.sh all
          mv bin/ ../..
          cd ../..

      - name: Zip files
        run: zip -r xpwn_linux.zip bin/

      - name: Update latest release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: latest
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: xpwn_linux.zip

  idevicererestore-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run compile script
        run: |
          cd ./src/idevicererestore
          ./compile.sh
          mv idevicerestore/bin/idevicerestore_linux ../../idevicererestore_linux
          cd ../..

      - name: Zip files
        run: zip -r idevicererestore_linux.zip idevicererestore_linux

      - name: Update latest release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: idevicererestore_linux.zip
